### Site Settings ###
title               : Ugur's Portfolio
description         : >-
                      "I turn coffee :coffee: into code,
                      use tabs over spaces
                      and never broke production."
baseurl             : "/"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : ugurkoysuren/ugurkoysuren.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Ugur Köysüren
  image             : http://ugurkoysuren.github.io/pages/ugur.jpeg
# behance           : your_username
# dribbble          : your_username
  email             : ugurkoysuren@gmail.com
# facebook          : your_username
  github            : ugurkoysuren
# gitlab            : your_username
# instagram         : your_username
  linkedin          : koysurenugur
  medium            : ugurkoysuren
# soundcloud        : your_username
  spotify           : ugurkoysuren
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : ugurkoysuren
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"



### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
